# Generated by Django 4.1 on 2022-09-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_position', models.CharField(max_length=32)),
                ('desired_position_en', models.CharField(max_length=32, null=True)),
                ('desired_position_ru', models.CharField(max_length=32, null=True)),
                ('summary', models.CharField(max_length=1024)),
                ('summary_en', models.CharField(max_length=1024, null=True)),
                ('summary_ru', models.CharField(max_length=1024, null=True)),
                ('name', models.CharField(max_length=32)),
                ('name_en', models.CharField(max_length=32, null=True)),
                ('name_ru', models.CharField(max_length=32, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=32)),
                ('e_mail', models.EmailField(max_length=254)),
                ('site', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('institution', models.CharField(max_length=64)),
                ('institution_en', models.CharField(max_length=64, null=True)),
                ('institution_ru', models.CharField(max_length=64, null=True)),
                ('start_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('degree', models.CharField(max_length=32)),
                ('degree_en', models.CharField(max_length=32, null=True)),
                ('degree_ru', models.CharField(max_length=32, null=True)),
                ('speciality', models.CharField(max_length=32)),
                ('speciality_en', models.CharField(max_length=32, null=True)),
                ('speciality_ru', models.CharField(max_length=32, null=True)),
                ('qualification', models.CharField(max_length=32)),
                ('qualification_en', models.CharField(max_length=32, null=True)),
                ('qualification_ru', models.CharField(max_length=32, null=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('program_langs', models.JSONField()),
                ('other', models.JSONField()),
                ('languages', models.JSONField()),
                ('languages_en', models.JSONField(null=True)),
                ('languages_ru', models.JSONField(null=True)),
                ('soft_skills', models.JSONField()),
                ('soft_skills_en', models.JSONField(null=True)),
                ('soft_skills_ru', models.JSONField(null=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=32)),
                ('organization_name_en', models.CharField(max_length=32, null=True)),
                ('organization_name_ru', models.CharField(max_length=32, null=True)),
                ('position', models.CharField(blank=True, max_length=32)),
                ('position_en', models.CharField(blank=True, max_length=32, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=32, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('fire_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=512)),
                ('description_en', models.CharField(max_length=512, null=True)),
                ('description_ru', models.CharField(max_length=512, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
        ),
    ]
